# Reference: https://aka.ms/yaml
# Things to note:
#   - Powershell session profiles do not work because the scripts are run with -NoProfile

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: sudo npm install -g markdown-styles
  displayName: Install tools
- script: make
  displayName: Build help pages
- task: DownloadSecureFile@1
  inputs:
    secureFile: deploy_key
  displayName: 'Get the deploy key'
- script: |
    mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
    chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    git remote set-url --push origin git@github.com:ztl8702/adfd.git
  displayName: 'Setup deploy key'
  condition: |
    and(not(eq(variables['Build.Reason'], 'PullRequest')),
        eq(variables['Build.SourceBranch'], 'refs/heads/master'))
- script: |
    cp -rf ./build /tmp/
    git remote update
    git fetch
    git checkout gh-pages
    git checkout -b gh-pages-new
    git reset --hard origin/gh-pages
    git rm -r '*'
    rm -rf ./*
    cp -rf /tmp/build/* ./
    git add .
    git config --local user.name "Azure Pipelines"
    git config --local user.email "azuredevops@microsoft.com"
    git commit --message "Azure DevOps Build ***NO_CI***"
    git checkout gh-pages
    git reset --hard gh-pages-new --
    git push --force origin gh-pages
  condition: |
    and(not(eq(variables['Build.Reason'], 'PullRequest')),
        eq(variables['Build.SourceBranch'], 'refs/heads/master'))